# Generated by Django 4.1.2 on 2022-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='covers/default_cover.jpeg', upload_to='covers/'),
        ),
    ]
