# Generated by Django 4.1.2 on 2022-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='media/covers/default_cover.jpeg', upload_to='media/covers/'),
        ),
    ]
