# Generated by Django 4.1.2 on 2022-12-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_news_text_alter_game_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
